# Generated by Django 4.2 on 2023-06-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
