# Generated by Django 4.2 on 2023-06-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_rename_image_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
