# Generated by Django 4.2 on 2023-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_image_url_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_processed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
