# Generated by Django 4.2 on 2023-07-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
